[2024-06-21T00:31:19.973+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-21T00:31:20.016+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemons.getpokemons manual__2024-06-21T00:31:17.883726+00:00 [queued]>
[2024-06-21T00:31:20.028+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemons.getpokemons manual__2024-06-21T00:31:17.883726+00:00 [queued]>
[2024-06-21T00:31:20.029+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-21T00:31:20.051+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): getpokemons> on 2024-06-21 00:31:17.883726+00:00
[2024-06-21T00:31:20.062+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=19975) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-21T00:31:20.064+0000] {standard_task_runner.py:63} INFO - Started process 19977 to run task
[2024-06-21T00:31:20.064+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pokemons', 'getpokemons', 'manual__2024-06-21T00:31:17.883726+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/python_operators.py', '--cfg-path', '/tmp/tmp0ocp57ub']
[2024-06-21T00:31:20.068+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask getpokemons
[2024-06-21T00:31:20.119+0000] {task_command.py:426} INFO - Running <TaskInstance: pokemons.getpokemons manual__2024-06-21T00:31:17.883726+00:00 [running]> on host 91fb71641d4b
[2024-06-21T00:31:20.231+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pokemons' AIRFLOW_CTX_TASK_ID='getpokemons' AIRFLOW_CTX_EXECUTION_DATE='2024-06-21T00:31:17.883726+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-21T00:31:17.883726+00:00'
[2024-06-21T00:31:20.233+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-21T00:31:20.234+0000] {logging_mixin.py:188} INFO - getting: https://pokeapi.co/api/v2/pokemon/?offset=0&limit=0
[2024-06-21T00:31:20.234+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-21T00:31:20.235+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/python_operators.py", line 25, in getpokemons
    output = output + requests.get(endpoint).json()['results']
                      ^^^^^^^^
NameError: name 'requests' is not defined
[2024-06-21T00:31:20.251+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pokemons, task_id=getpokemons, run_id=manual__2024-06-21T00:31:17.883726+00:00, execution_date=20240621T003117, start_date=20240621T003120, end_date=20240621T003120
[2024-06-21T00:31:20.269+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 42 for task getpokemons (name 'requests' is not defined; 19977)
[2024-06-21T00:31:20.318+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-21T00:31:20.344+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-21T00:31:20.349+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
