[2024-06-23T00:08:47.149+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-23T00:08:47.186+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemon_example.metricspokemonweights manual__2024-06-23T00:05:08.961109+00:00 [queued]>
[2024-06-23T00:08:47.197+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemon_example.metricspokemonweights manual__2024-06-23T00:05:08.961109+00:00 [queued]>
[2024-06-23T00:08:47.198+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-23T00:08:47.217+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): metricspokemonweights> on 2024-06-23 00:05:08.961109+00:00
[2024-06-23T00:08:47.226+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5736) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-23T00:08:47.228+0000] {standard_task_runner.py:63} INFO - Started process 5737 to run task
[2024-06-23T00:08:47.228+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pokemon_example', 'metricspokemonweights', 'manual__2024-06-23T00:05:08.961109+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/python_operators.py', '--cfg-path', '/tmp/tmpah8pr9fq']
[2024-06-23T00:08:47.229+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask metricspokemonweights
[2024-06-23T00:08:47.282+0000] {task_command.py:426} INFO - Running <TaskInstance: pokemon_example.metricspokemonweights manual__2024-06-23T00:05:08.961109+00:00 [running]> on host c357804a93ab
[2024-06-23T00:08:47.387+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pokemon_example' AIRFLOW_CTX_TASK_ID='metricspokemonweights' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T00:05:08.961109+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-23T00:05:08.961109+00:00'
[2024-06-23T00:08:47.388+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-23T00:08:47.389+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv6qgj56po --system-site-packages --python=python
[2024-06-23T00:08:47.390+0000] {process_utils.py:187} INFO - Output:
[2024-06-23T00:08:48.158+0000] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 253ms
[2024-06-23T00:08:48.159+0000] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venv6qgj56po, clear=False, no_vcs_ignore=False, global=True)
[2024-06-23T00:08:48.160+0000] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-06-23T00:08:48.160+0000] {process_utils.py:191} INFO -     added seed packages: pip==24.0
[2024-06-23T00:08:48.161+0000] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-06-23T00:08:48.185+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venv6qgj56po/bin/pip install -r /tmp/venv6qgj56po/requirements.txt
[2024-06-23T00:08:48.186+0000] {process_utils.py:187} INFO - Output:
[2024-06-23T00:08:53.423+0000] {process_utils.py:191} INFO - 
[2024-06-23T00:08:53.424+0000] {process_utils.py:191} INFO - [notice] A new release of pip is available: 24.0 -> 24.1
[2024-06-23T00:08:53.425+0000] {process_utils.py:191} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-06-23T00:08:53.526+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venv6qgj56po/bin/python /tmp/venv-callvifm4z33/script.py /tmp/venv-callvifm4z33/script.in /tmp/venv-callvifm4z33/script.out /tmp/venv-callvifm4z33/string_args.txt /tmp/venv-callvifm4z33/termination.log
[2024-06-23T00:08:53.527+0000] {process_utils.py:187} INFO - Output:
[2024-06-23T00:08:55.698+0000] {process_utils.py:191} INFO - ----------------------------------------------------------------------------------------------------
[2024-06-23T00:08:55.699+0000] {process_utils.py:191} INFO - clusters detail:
[2024-06-23T00:08:55.699+0000] {process_utils.py:191} INFO - {
[2024-06-23T00:08:55.700+0000] {process_utils.py:191} INFO -     "n_clusters": 3,
[2024-06-23T00:08:55.701+0000] {process_utils.py:191} INFO -     "centroids": [
[2024-06-23T00:08:55.702+0000] {process_utils.py:191} INFO -         88.50000000000006,
[2024-06-23T00:08:55.702+0000] {process_utils.py:191} INFO -         919.9999999999999,
[2024-06-23T00:08:55.702+0000] {process_utils.py:191} INFO -         307.0
[2024-06-23T00:08:55.703+0000] {process_utils.py:191} INFO -     ]
[2024-06-23T00:08:55.703+0000] {process_utils.py:191} INFO - }
[2024-06-23T00:08:55.704+0000] {process_utils.py:191} INFO - ----------------------------------------------------------------------------------------------------
[2024-06-23T00:08:55.704+0000] {process_utils.py:191} INFO - weight statistics:
[2024-06-23T00:08:55.704+0000] {process_utils.py:191} INFO - {
[2024-06-23T00:08:55.705+0000] {process_utils.py:191} INFO -     "max": 1000,
[2024-06-23T00:08:55.705+0000] {process_utils.py:191} INFO -     "min": 18,
[2024-06-23T00:08:55.705+0000] {process_utils.py:191} INFO -     "mean": 267.85,
[2024-06-23T00:08:55.706+0000] {process_utils.py:191} INFO -     "median": 157.5,
[2024-06-23T00:08:55.706+0000] {process_utils.py:191} INFO -     "stdev:": 301.90435484385483
[2024-06-23T00:08:55.706+0000] {process_utils.py:191} INFO - }
[2024-06-23T00:08:55.707+0000] {process_utils.py:191} INFO - ----------------------------------------------------------------------------------------------------
[2024-06-23T00:08:55.707+0000] {process_utils.py:191} INFO - anonymized information:
[2024-06-23T00:08:55.707+0000] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-06-23T00:08:55.707+0000] {process_utils.py:191} INFO -   File "/tmp/venv-callvifm4z33/script.py", line 75, in <module>
[2024-06-23T00:08:55.707+0000] {process_utils.py:191} INFO -     res = metricspokemonweights(*arg_dict["args"], **arg_dict["kwargs"])
[2024-06-23T00:08:55.708+0000] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-23T00:08:55.708+0000] {process_utils.py:191} INFO -   File "/tmp/venv-callvifm4z33/script.py", line 44, in metricspokemonweights
[2024-06-23T00:08:55.709+0000] {process_utils.py:191} INFO -     print(tabulate.tabulate(outp2), headers='keys')
[2024-06-23T00:08:55.709+0000] {process_utils.py:191} INFO - TypeError: 'headers' is an invalid keyword argument for print()
[2024-06-23T00:08:56.053+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-23T00:08:56.063+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
'headers' is an invalid keyword argument for print()
[2024-06-23T00:08:56.070+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pokemon_example, task_id=metricspokemonweights, run_id=manual__2024-06-23T00:05:08.961109+00:00, execution_date=20240623T000508, start_date=20240623T000847, end_date=20240623T000856
[2024-06-23T00:08:56.094+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task metricspokemonweights (Process returned non-zero exit status 1.
'headers' is an invalid keyword argument for print(); 5737)
[2024-06-23T00:08:56.140+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-23T00:08:56.156+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-23T00:08:56.159+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
