[2024-06-21T00:56:26.548+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-21T00:56:26.569+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemons.getpokemons manual__2024-06-21T00:56:25.369436+00:00 [queued]>
[2024-06-21T00:56:26.580+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemons.getpokemons manual__2024-06-21T00:56:25.369436+00:00 [queued]>
[2024-06-21T00:56:26.580+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-21T00:56:26.601+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): getpokemons> on 2024-06-21 00:56:25.369436+00:00
[2024-06-21T00:56:26.607+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=193) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-21T00:56:26.608+0000] {standard_task_runner.py:63} INFO - Started process 194 to run task
[2024-06-21T00:56:26.609+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pokemons', 'getpokemons', 'manual__2024-06-21T00:56:25.369436+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/python_operators.py', '--cfg-path', '/tmp/tmp2egeyc3q']
[2024-06-21T00:56:26.610+0000] {standard_task_runner.py:91} INFO - Job 51: Subtask getpokemons
[2024-06-21T00:56:26.652+0000] {task_command.py:426} INFO - Running <TaskInstance: pokemons.getpokemons manual__2024-06-21T00:56:25.369436+00:00 [running]> on host f9f27b1b4edb
[2024-06-21T00:56:26.745+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pokemons' AIRFLOW_CTX_TASK_ID='getpokemons' AIRFLOW_CTX_EXECUTION_DATE='2024-06-21T00:56:25.369436+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-21T00:56:25.369436+00:00'
[2024-06-21T00:56:26.746+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-21T00:56:26.747+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvimkekdrt --system-site-packages --python=python
[2024-06-21T00:56:26.748+0000] {process_utils.py:187} INFO - Output:
[2024-06-21T00:56:27.992+0000] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 662ms
[2024-06-21T00:56:27.992+0000] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venvimkekdrt, clear=False, no_vcs_ignore=False, global=True)
[2024-06-21T00:56:27.993+0000] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-06-21T00:56:27.993+0000] {process_utils.py:191} INFO -     added seed packages: pip==24.0
[2024-06-21T00:56:27.993+0000] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-06-21T00:56:28.016+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venvimkekdrt/bin/pip install -r /tmp/venvimkekdrt/requirements.txt
[2024-06-21T00:56:28.017+0000] {process_utils.py:187} INFO - Output:
[2024-06-21T00:56:30.085+0000] {process_utils.py:191} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvimkekdrt/requirements.txt (line 1)) (2.31.0)
[2024-06-21T00:56:30.088+0000] {process_utils.py:191} INFO - Requirement already satisfied: tabulate in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvimkekdrt/requirements.txt (line 2)) (0.9.0)
[2024-06-21T00:56:30.097+0000] {process_utils.py:191} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.12/site-packages (from requests->-r /tmp/venvimkekdrt/requirements.txt (line 1)) (3.3.2)
[2024-06-21T00:56:30.098+0000] {process_utils.py:191} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.12/site-packages (from requests->-r /tmp/venvimkekdrt/requirements.txt (line 1)) (3.7)
[2024-06-21T00:56:30.100+0000] {process_utils.py:191} INFO - Requirement already satisfied: urllib3<3,>=1.21.1 in /home/***/.local/lib/python3.12/site-packages (from requests->-r /tmp/venvimkekdrt/requirements.txt (line 1)) (2.2.1)
[2024-06-21T00:56:30.101+0000] {process_utils.py:191} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.12/site-packages (from requests->-r /tmp/venvimkekdrt/requirements.txt (line 1)) (2024.2.2)
[2024-06-21T00:56:33.023+0000] {process_utils.py:191} INFO - 
[2024-06-21T00:56:33.023+0000] {process_utils.py:191} INFO - [notice] A new release of pip is available: 24.0 -> 24.1
[2024-06-21T00:56:33.023+0000] {process_utils.py:191} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-06-21T00:56:33.131+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venvimkekdrt/bin/python /tmp/venv-callj8bkrn08/script.py /tmp/venv-callj8bkrn08/script.in /tmp/venv-callj8bkrn08/script.out /tmp/venv-callj8bkrn08/string_args.txt /tmp/venv-callj8bkrn08/termination.log
[2024-06-21T00:56:33.132+0000] {process_utils.py:187} INFO - Output:
[2024-06-21T00:56:35.382+0000] {process_utils.py:191} INFO - getting: https://pokeapi.co/api/v2/pokemon/?offset=0&limit=0
[2024-06-21T00:56:35.383+0000] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-06-21T00:56:35.383+0000] {process_utils.py:191} INFO -   File "/tmp/venv-callj8bkrn08/script.py", line 53, in <module>
[2024-06-21T00:56:35.384+0000] {process_utils.py:191} INFO -     res = getpokemons(*arg_dict["args"], **arg_dict["kwargs"])
[2024-06-21T00:56:35.384+0000] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-21T00:56:35.385+0000] {process_utils.py:191} INFO -   File "/tmp/venv-callj8bkrn08/script.py", line 23, in getpokemons
[2024-06-21T00:56:35.385+0000] {process_utils.py:191} INFO -     output = output + requests.get(endpoint).json()['results']
[2024-06-21T00:56:35.385+0000] {process_utils.py:191} INFO -                       ^^^^^^^^
[2024-06-21T00:56:35.386+0000] {process_utils.py:191} INFO - NameError: name 'requests' is not defined
[2024-06-21T00:56:35.614+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-21T00:56:35.623+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
name 'requests' is not defined
[2024-06-21T00:56:35.627+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pokemons, task_id=getpokemons, run_id=manual__2024-06-21T00:56:25.369436+00:00, execution_date=20240621T005625, start_date=20240621T005626, end_date=20240621T005635
[2024-06-21T00:56:35.651+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 51 for task getpokemons (Process returned non-zero exit status 1.
name 'requests' is not defined; 194)
[2024-06-21T00:56:35.687+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-21T00:56:35.727+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-21T00:56:35.735+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
