[2024-06-21T01:16:58.385+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-21T01:16:58.411+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemons.metricspokemonweights manual__2024-06-21T01:16:34.034582+00:00 [queued]>
[2024-06-21T01:16:58.421+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemons.metricspokemonweights manual__2024-06-21T01:16:34.034582+00:00 [queued]>
[2024-06-21T01:16:58.422+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-21T01:16:58.435+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): metricspokemonweights> on 2024-06-21 01:16:34.034582+00:00
[2024-06-21T01:16:58.441+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=213) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-21T01:16:58.443+0000] {standard_task_runner.py:63} INFO - Started process 214 to run task
[2024-06-21T01:16:58.443+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pokemons', 'metricspokemonweights', 'manual__2024-06-21T01:16:34.034582+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/python_operators.py', '--cfg-path', '/tmp/tmp44dku6a3']
[2024-06-21T01:16:58.445+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask metricspokemonweights
[2024-06-21T01:16:58.494+0000] {task_command.py:426} INFO - Running <TaskInstance: pokemons.metricspokemonweights manual__2024-06-21T01:16:34.034582+00:00 [running]> on host c357804a93ab
[2024-06-21T01:16:58.596+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pokemons' AIRFLOW_CTX_TASK_ID='metricspokemonweights' AIRFLOW_CTX_EXECUTION_DATE='2024-06-21T01:16:34.034582+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-21T01:16:34.034582+00:00'
[2024-06-21T01:16:58.597+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-21T01:16:58.598+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv6krpb2ck --system-site-packages --python=python
[2024-06-21T01:16:58.599+0000] {process_utils.py:187} INFO - Output:
[2024-06-21T01:16:59.319+0000] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 236ms
[2024-06-21T01:16:59.320+0000] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venv6krpb2ck, clear=False, no_vcs_ignore=False, global=True)
[2024-06-21T01:16:59.321+0000] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-06-21T01:16:59.321+0000] {process_utils.py:191} INFO -     added seed packages: pip==24.0
[2024-06-21T01:16:59.322+0000] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-06-21T01:16:59.348+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venv6krpb2ck/bin/pip install -r /tmp/venv6krpb2ck/requirements.txt
[2024-06-21T01:16:59.349+0000] {process_utils.py:187} INFO - Output:
[2024-06-21T01:17:04.971+0000] {process_utils.py:191} INFO - 
[2024-06-21T01:17:04.972+0000] {process_utils.py:191} INFO - [notice] A new release of pip is available: 24.0 -> 24.1
[2024-06-21T01:17:04.972+0000] {process_utils.py:191} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-06-21T01:17:05.079+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venv6krpb2ck/bin/python /tmp/venv-callqdigian4/script.py /tmp/venv-callqdigian4/script.in /tmp/venv-callqdigian4/script.out /tmp/venv-callqdigian4/string_args.txt /tmp/venv-callqdigian4/termination.log
[2024-06-21T01:17:05.079+0000] {process_utils.py:187} INFO - Output:
[2024-06-21T01:17:07.357+0000] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-06-21T01:17:07.357+0000] {process_utils.py:191} INFO -   File "/tmp/venv-callqdigian4/script.py", line 55, in <module>
[2024-06-21T01:17:07.358+0000] {process_utils.py:191} INFO -     res = metricspokemonweights(*arg_dict["args"], **arg_dict["kwargs"])
[2024-06-21T01:17:07.358+0000] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-21T01:17:07.358+0000] {process_utils.py:191} INFO -   File "/tmp/venv-callqdigian4/script.py", line 27, in metricspokemonweights
[2024-06-21T01:17:07.358+0000] {process_utils.py:191} INFO -     print(json.dumps(outp, indent=4))
[2024-06-21T01:17:07.359+0000] {process_utils.py:191} INFO -           ^^^^
[2024-06-21T01:17:07.359+0000] {process_utils.py:191} INFO - NameError: name 'json' is not defined. Did you forget to import 'json'?
[2024-06-21T01:17:07.598+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-21T01:17:07.608+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
name 'json' is not defined
[2024-06-21T01:17:07.612+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pokemons, task_id=metricspokemonweights, run_id=manual__2024-06-21T01:16:34.034582+00:00, execution_date=20240621T011634, start_date=20240621T011658, end_date=20240621T011707
[2024-06-21T01:17:07.634+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 64 for task metricspokemonweights (Process returned non-zero exit status 1.
name 'json' is not defined; 214)
[2024-06-21T01:17:07.683+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-21T01:17:07.714+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-21T01:17:07.720+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
